test destroy and revert

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,17 +21,16 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            cd backend
-            sudo apt update && sudo apt upgrade
-            sudo apt install curl
-            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUKET}/migration_<< parameters.Workflow_ID >>)
-            echo $SUCCESS
-            if (( $SUCCESS == 1 ));
-            then
-              # cd ~/project/backend
+            # sudo apt update && sudo apt upgrade
+            # sudo apt install curl
+            # SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUKET}/migration_<< parameters.Workflow_ID >>)
+            # echo $SUCCESS
+            # if (( $SUCCESS == 1 ));
+            # then
+              cd ~/project/backend
               npm install
               npm run migration:revert
-            fi
+            # fi
 jobs:
   build-frontend:
     docker:
@@ -264,10 +263,10 @@ jobs:
             if curl -s $backendUrl | grep "ok"
             then
               echo "Smoke tests finished with success"
-              exit 0
+              exit 1
             else
               echo "Smoke tests finished with failure"
-              exit 0
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -281,8 +280,8 @@ jobs:
               return 0
             fi
 
-      # - destroy-environment   
-      # - revert-migrations 
+      - destroy-environment   
+      - revert-migrations 
 
       # Here's where you will add some code to rollback on failure    
 
@@ -352,10 +351,10 @@ workflows:
           requires: [run-migrations,deploy-backend]
       - deploy-backend:
           requires: [run-migrations]  
-      # - smoke-test:       
-      #     requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-            requires: [deploy-backend, deploy-frontend]
+      - smoke-test      
+          requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #       requires: [deploy-backend, deploy-frontend]
       #     requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update] 
+      # - cleanup:
+      #     requires: [cloudfront-update] 
